# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d125eb9639962c861b967e63e1bc4f7a3b7c32a6f0c9ff72ebbb65a03572a78ec9d1275bfc029dd214ed1e10b871bd7c13cea02dfc9cbb40cf2373880479c1af

test:
  secret_key_base: 40d7f53afb7630e5b6983b649b102afe418732e2e1e632f58ccf075e32bbf168c57609adb2c754e3f98097b579ded6b3ec14ca1620c936702698eb229a1c81a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
